AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Messages mover

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3


Resources:

    MoveMessagesFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: sqs_msgs_mover/
            Handler: app.lambda_handler
            Runtime: nodejs8.10
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Events:
                MoveMessages:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /run
                        Method: get

Outputs:

    MoveMessagesApi:
      Description: "API Gateway endpoint URL for Prod stage for MoveMessages function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/run/"

    MoveMessagesFunction:
      Description: "MoveMessages Lambda Function ARN"
      Value: !GetAtt MoveMessagesFunction.Arn

    MoveMessagesFunctionIamRole:
      Description: "Implicit IAM Role created for MoveMessages function"
      Value: !GetAtt MoveMessagesFunctionRole.Arn
