AWSTemplateFormatVersion: 2010-09-09
Description: SQS source and target for serverless workshop
Resources:
    SourceQueue:
      Type: "AWS::SQS::Queue"
    TargetQueue:
      Type: "AWS::SQS::Queue"
Outputs:
    SourceQueueUrl:
      Description: "SourceQueue Url"
      Value: !Ref SourceQueue
    TargetQueueUrl:
      Description: "TargetQueue Url"
      Value: !Ref TargetQueue
